[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags = 
lib_deps = 
	https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12
	tzapu/WiFiManager@^2.0.16-rc.2
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
